### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by otherguy** [padcom/array-prototype-functions#3]
I'm confused on how to use this with NodeJS. I immediately get `Unexpected token 'export'` on some modules, and `SyntaxError: Cannot use import statement outside a module` on others.

Running `node` v15.7.0.

I appreciate your help!

```
./node_modules/array-prototype-functions/avg.js:12
export {};
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (node:internal/modules/cjs/loader:1024:16)
    at Module._compile (node:internal/modules/cjs/loader:1072:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (./server.js:10:18)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
```

```
import './blank-module';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

**Comment by padcom** [comment]
It'd be good to know which version of node are you using.

**Comment by otherguy** [comment]
Thanks for the quick answer! I had just edited the ticket before you posted. I'm running `node` v15.7.0.

**Comment by otherguy** [comment]
Thanks for the quick answer! I had just edited the ticket before you posted. I'm running `node` v15.7.0.

```bash
# ├─ array-prototype-functions@2.10.0
$  node
Welcome to Node.js v15.7.0.
Type ".help" for more information.
> require('array-prototype-functions/avg')
./node_modules/array-prototype-functions/avg.js:12
export {};
^^^^^^

Uncaught SyntaxError: Unexpected token 'export'
```

https://npm.runkit.com/array-prototype-functions shows the same error.

**Comment by padcom** [comment]
To be honest I never used it from node.js :) But don't worry. I've got this.

**Comment by otherguy** [comment]
Neat! 

It looks like a great set of extensions to `Array`. I'm doing some data table manipulation that will need a few of the methods you wrote here!

**Comment by padcom** [comment]
I have downgraded the transpilation level from ES6 to ES5 and changed modules to commonjs which should make it possible now to use it directly from node.js.

```
#!/usr/bin/env node

require('array-prototype-functions/sum')
require('array-prototype-functions/avg')

console.log([ 1, 2, 3 ].avg())
```

**Comment by padcom** [comment]
Try version 2.11 - it should work for you now.

**Comment by otherguy** [comment]
That was insanely fast. I can confirm, `2.11` works just fine and I can import all modules.

Thank you for creating this, it makes my work a lot easier!

**Comment by padcom** [comment]
I've checked it also with a Vue web app (where I primarily use it - will close the ticket now.

Thanks for using it :) It validates my work makes sense :)
